ALTER SEQUENCE project_period_project_period_id_seq RESTART WITH 1;

INSERT INTO public.project_period (id, project_id, period_id) VALUES (1, 1, 2);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (2, 2, 2);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (3, 3, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (4, 4, 2);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (5, 5, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (6, 6, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (7, 7, 4);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (8, 8, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (9, 9, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (10, 10, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (11, 11, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (12, 12, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (13, 13, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (14, 14, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (15, 15, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (16, 16, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (17, 17, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (18, 18, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (19, 19, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (20, 20, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (21, 21, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (22, 22, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (23, 23, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (24, 24, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (25, 25, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (26, 26, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (27, 27, 3);
INSERT INTO public.project_period (id, project_id, period_id) VALUES (28, 28, 3);

ALTER SEQUENCE project_period_project_period_id_seq RESTART WITH 29;