module.exports = {
  userDB: require('./user'),
  projectDB: require('./project'),
  typeDB: require('./type'),
  tagDB: require('./tag'),
  positionDB: require('./position'),
  periodDB: require('./period'),
  goalDB: require('./goal'),
  fieldDB: require('./field'),
  userPositionDB: require('./userPosition'),
  userFieldDB: require('./userField'),
  projectPeriodDB: require('./projectPeriod'),
  projectPositionDB: require('./projectPosition'),
  projectGoalDB: require('./projectGoal'),
  projectTagDB: require('./projectTag'),
  projectFieldDB: require('./projectField'),
  memberDB: require('./member'),
};
