openapi: 3.0.0
info:
  version: 1.0.0
  title: Teamble
  description: Teamble의 api 명세서
servers:
  - url: http://localhost:5005/api-docs/
paths:
  /:
    $ref: './paths/common.yaml'
  /auth/signup/metadata:
    $ref: './paths/auth/authSignupMetadata.yaml'
  /auth/signup:
    $ref: './paths/auth/authSignup.yaml'
  /project/top:
    $ref: './paths/project/projectTop.yaml'
  /user/profile/{userId}:
    $ref: './paths/user/userProfileUserId.yaml'
components:
  schemas:
    $ref: './schemas/_index.yaml'
  responses:
    $ref: './responses/_index.yaml'
